INSERT INTO user(id_user,username,email, password) VALUES (1,'testowyuser01','testowyuser01@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (2,'testowyuser02','testowyuser02@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (3,'testowyuser03','testowyuser03@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (4,'testowyuser04','testowyuser04@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (5,'testowyuser05','testowyuser05@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (6,'testowyuser06','testowyuser06@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (7,'testowyuser07','testowyuser07@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (8,'testowyuser08','testowyuser08@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (9,'testowyuser09','testowyuser09@test.pl', 'testowyuser123456789' );
INSERT INTO user(id_user,username,email, password) VALUES (10,'testowyuser10','testowyuser10@test.pl', 'testowyuser123456789' );

INSERT INTO  follower(id_follower,id_followee) VALUES (1,3);
INSERT INTO  follower(id_follower,id_followee) VALUES (1,5);
INSERT INTO  follower(id_follower,id_followee) VALUES (1,6);
INSERT INTO  follower(id_follower,id_followee) VALUES (1,7);
INSERT INTO  follower(id_follower,id_followee) VALUES (2,1);
INSERT INTO  follower(id_follower,id_followee) VALUES (2,3);
INSERT INTO  follower(id_follower,id_followee) VALUES (2,10);
INSERT INTO  follower(id_follower,id_followee) VALUES (3,7);
INSERT INTO  follower(id_follower,id_followee) VALUES (3,9);
INSERT INTO  follower(id_follower,id_followee) VALUES (3,10);
INSERT INTO  follower(id_follower,id_followee) VALUES (4,3);
INSERT INTO  follower(id_follower,id_followee) VALUES (4,1);
INSERT INTO  follower(id_follower,id_followee) VALUES (4,5);
INSERT INTO  follower(id_follower,id_followee) VALUES (5,2);
INSERT INTO  follower(id_follower,id_followee) VALUES (5,4);
INSERT INTO  follower(id_follower,id_followee) VALUES (5,7);
INSERT INTO  follower(id_follower,id_followee) VALUES (6,7);
INSERT INTO  follower(id_follower,id_followee) VALUES (6,8);
INSERT INTO  follower(id_follower,id_followee) VALUES (6,9);
INSERT INTO  follower(id_follower,id_followee) VALUES (7,10);
INSERT INTO  follower(id_follower,id_followee) VALUES (7,9);
INSERT INTO  follower(id_follower,id_followee) VALUES (7,2);
INSERT INTO  follower(id_follower,id_followee) VALUES (8,2);
INSERT INTO  follower(id_follower,id_followee) VALUES (8,3);
INSERT INTO  follower(id_follower,id_followee) VALUES (8,7);
INSERT INTO  follower(id_follower,id_followee) VALUES (9,10);
INSERT INTO  follower(id_follower,id_followee) VALUES (9,1);
INSERT INTO  follower(id_follower,id_followee) VALUES (9,2);
INSERT INTO  follower(id_follower,id_followee) VALUES (10,3);
INSERT INTO  follower(id_follower,id_followee) VALUES (10,4);
INSERT INTO  follower(id_follower,id_followee) VALUES (10,5);
INSERT INTO  follower(id_follower,id_followee) VALUES (10,7);

INSERT  INTO message(id_author,text,publication_date)VALUES (1,'tekst wprowadzony przez testowyuser01',TIMESTAMP '2017-01-03 01:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (1,'tekst wprowadzony przez testowyuser01',TIMESTAMP '2017-02-02 01:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (1,'tekst wprowadzony przez testowyuser01',TIMESTAMP '2017-03-04 01:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (2,'tekst wprowadzony przez testowyuser02',TIMESTAMP '2017-04-05 02:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (2,'tekst wprowadzony przez testowyuser02',TIMESTAMP '2017-05-02 02:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (2,'tekst wprowadzony przez testowyuser02',TIMESTAMP '2017-01-23 02:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (3,'tekst wprowadzony przez testowyuser03',TIMESTAMP '2017-06-01 03:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (3,'tekst wprowadzony przez testowyuser03',TIMESTAMP '2017-05-21 03:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (3,'tekst wprowadzony przez testowyuser03',TIMESTAMP '2017-05-01 03:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (4,'tekst wprowadzony przez testowyuser04',TIMESTAMP '2017-05-05 04:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (4,'tekst wprowadzony przez testowyuser04',TIMESTAMP '2017-01-05 04:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (4,'tekst wprowadzony przez testowyuser04',TIMESTAMP '2017-02-05 04:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (5,'tekst wprowadzony przez testowyuser05',TIMESTAMP '2017-03-02 05:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (5,'tekst wprowadzony przez testowyuser05',TIMESTAMP '2017-05-03 05:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (5,'tekst wprowadzony przez testowyuser05',TIMESTAMP '2017-04-04 05:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (6,'tekst wprowadzony przez testowyuser06',TIMESTAMP '2017-01-01 06:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (6,'tekst wprowadzony przez testowyuser06',TIMESTAMP '2017-02-07 06:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (6,'tekst wprowadzony przez testowyuser06',TIMESTAMP '2017-03-09 06:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (7,'tekst wprowadzony przez testowyuser07',TIMESTAMP '2017-04-10 07:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (7,'tekst wprowadzony przez testowyuser07',TIMESTAMP '2017-01-05 07:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (7,'tekst wprowadzony przez testowyuser07',TIMESTAMP '2017-02-10 07:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (8,'tekst wprowadzony przez testowyuser08',TIMESTAMP '2017-03-21 08:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (8,'tekst wprowadzony przez testowyuser08',TIMESTAMP '2017-04-12 08:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (8,'tekst wprowadzony przez testowyuser08',TIMESTAMP '2017-05-24 08:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (9,'tekst wprowadzony przez testowyuser09',TIMESTAMP '2017-05-25 09:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (9,'tekst wprowadzony przez testowyuser09',TIMESTAMP '2017-05-01 09:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (9,'tekst wprowadzony przez testowyuser09',TIMESTAMP '2017-05-30 09:01:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (10,'tekst wprowadzony przez testowyuser10',TIMESTAMP '2017-05-22 10:00:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (10,'tekst wprowadzony przez testowyuser10',TIMESTAMP '2017-05-05 10:02:00');
INSERT  INTO message(id_author,text,publication_date)VALUES (10,'tekst wprowadzony przez testowyuser10',TIMESTAMP '2017-05-05 10:01:00');
